name: Client CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: './client/package-lock.json'

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.IONOS_SSH_PRIVATE_KEY }}

      - name: Deploy via Rsync
        run: |
          rsync -avz ./client/dist/ ${{ secrets.IONOS_USER }}@${{ secrets.IONOS_HOST }}:/var/www/momenti/client/dist/
